[package]
name = "decode-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = { version = "6.0", features = ["static"], git = "https://github.com/yanghaku/rust-ffmpeg.git", branch = "wasm32-wasi" }
